[build]
  base = "classy-mobile-backend"
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "https://github.com/JorgeBoscanClassy/hackathon-classy-mobile"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200